# Generated by Django 3.2.16 on 2023-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=40)),
                ('lavozimi', models.CharField(max_length=20)),
                ('malumot', models.TextField()),
                ('link', models.CharField(max_length=60)),
            ],
        ),
    ]
