# Generated by Django 3.2.16 on 2023-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
