# Generated by Django 3.2.16 on 2023-02-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_alter_team_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myfiles.type'),
            preserve_default=False,
        ),
    ]
