# Generated by Django 3.2.16 on 2023-02-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_team_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='link',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='team',
            name='link2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
