# Generated by Django 3.2.16 on 2023-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_auto_20230206_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=65)),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
