# Generated by Django 3.2.16 on 2023-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_murojaat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obunamail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=65)),
            ],
        ),
    ]
